// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFhg7e7mc1rx3Xw183Q5G44SqxK34po8I',
    appId: '1:778966761242:web:b3ed1796e7813528e5b6a3',
    messagingSenderId: '778966761242',
    projectId: 'civicshield-3f197',
    authDomain: 'civicshield-3f197.firebaseapp.com',
    storageBucket: 'civicshield-3f197.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgEJaenjo4aMRVoExRvguKr6GBxwJbhi4',
    appId: '1:778966761242:android:a48d7d357081b49be5b6a3',
    messagingSenderId: '778966761242',
    projectId: 'civicshield-3f197',
    storageBucket: 'civicshield-3f197.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ36Q94pKTTM3CjkrvyHV3aWPdiCbYT6Y',
    appId: '1:778966761242:ios:96aec7958469d220e5b6a3',
    messagingSenderId: '778966761242',
    projectId: 'civicshield-3f197',
    storageBucket: 'civicshield-3f197.firebasestorage.app',
    iosBundleId: 'com.example.civicshieldapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQ36Q94pKTTM3CjkrvyHV3aWPdiCbYT6Y',
    appId: '1:778966761242:ios:96aec7958469d220e5b6a3',
    messagingSenderId: '778966761242',
    projectId: 'civicshield-3f197',
    storageBucket: 'civicshield-3f197.firebasestorage.app',
    iosBundleId: 'com.example.civicshieldapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFhg7e7mc1rx3Xw183Q5G44SqxK34po8I',
    appId: '1:778966761242:web:d1f751b169d3aafce5b6a3',
    messagingSenderId: '778966761242',
    projectId: 'civicshield-3f197',
    authDomain: 'civicshield-3f197.firebaseapp.com',
    storageBucket: 'civicshield-3f197.firebasestorage.app',
  );
}
